# Generated by Django 4.0.3 on 2022-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_credit',
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
